/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SC;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author melki
 */
public class CatalogoCuentas extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoCuentas
     */
    String ruta = "catalogo.txt";
    public CatalogoCuentas() {
        initComponents();
        setLocationRelativeTo(null);
        setDate(fecha);
        File f = new File(ruta);
        // Crea el key listener
numeroCuenta.addKeyListener(new KeyListener() {
@Override
public void keyTyped(KeyEvent e) {
// No se necesita implementar este método
}

@Override
public void keyPressed(KeyEvent e) {
// No se necesita implementar este método
}

@Override
public void keyReleased(KeyEvent e) {
// Si se ha presionado la tecla Enter
if (e.getKeyCode() == KeyEvent.VK_ENTER) {
// Llama al método searchAndModify
//searchAndModify(numeroCuenta, f);
}
}
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreCuenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        adm = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        nivel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        grupocOmb = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        padre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        debitoAco = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CreditoAco = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(597, 435));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(560, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel1.add(numeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 26, -1, 20));

        saldo.setForeground(new java.awt.Color(255, 255, 255));
        saldo.setText("0.00");
        jPanel1.add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, 30));

        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Modificando");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(nombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 160, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estructura");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 540, 10));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        adm.setBackground(new java.awt.Color(0, 51, 51));
        adm.setForeground(new java.awt.Color(255, 255, 255));
        adm.setText("General");
        jPanel1.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        normal.setForeground(new java.awt.Color(0, 51, 51));
        normal.setText("Detalle");
        jPanel1.add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nivel: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));
        jPanel1.add(nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Grupo: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        grupocOmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "PASIVO", "CAPITAL", "INGRESOS", "COSTOS", "GASTOS" }));
        jPanel1.add(grupocOmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 250, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Informacion de Transaccion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cuenta Cociliable: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Grupo de flujo de efectivo: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 160, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "EFECTIVO", "OPERATIVO", "INVERSIONES", "FINANCIERO", "" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reportar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, 20));

        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 10));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Padre: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Cracion: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 30));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hora:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 100, 30));

        aceptar.setBackground(new java.awt.Color(102, 255, 255));
        aceptar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aceptar.setForeground(new java.awt.Color(0, 0, 0));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 40));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Debito Acu.: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        debitoAco.setForeground(new java.awt.Color(255, 255, 255));
        debitoAco.setText("0.00");
        jPanel1.add(debitoAco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Credito Acu.: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        CreditoAco.setForeground(new java.awt.Color(255, 255, 255));
        CreditoAco.setText("0.00");
        jPanel1.add(CreditoAco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    public void searchAndModify(JTextField searchField, File file) {
// Obtiene el string de búsqueda
String searchString = searchField.getText();
// Abre el archivo para lectura
BufferedReader reader = null;
try {
reader = new BufferedReader(new FileReader(file));
} catch (FileNotFoundException ex) {
ex.printStackTrace();
return;
}

// Bandera que indica si se ha encontrado la línea correspondiente
boolean found = false;

// Almacena los valores de los campos de la línea encontrada
String field2Value = "";
String radioButtonValue = "";
String field4Value = "";
String comboBox1Value = "";
String checkBoxValue = "";
String comboBox2Value = "";
String field7Value = "";
String field8Value = "";
String label10Value = "";

// Almacena las líneas del archivo en una lista
List<String> lines = new ArrayList<>();
// Lee cada línea del archivo
String line;
try {
    while ((line = reader.readLine()) != null) {
        // Divide la línea en palabras separadas por "; "
        String[] words = line.split("; ");

        // Si la primera palabra es igual al string de búsqueda
        if (words[0].equals(searchString)) {
            // Se ha encontrado la línea correspondiente
            found = true;

            // Almacena los valores de los campos de la línea encontrada
            field2Value = words[1];
            radioButtonValue = words[2];
            field4Value = words[3];
            comboBox1Value = words[4];
            checkBoxValue = words[5];
comboBox2Value = words[6];
field7Value = words[7];
field8Value = words[8];
label10Value = words[9];
} else {
// Agrega la línea a la lista de líneas
lines.add(line);
}
}
} catch (IOException ex) {
ex.printStackTrace();
return;
}

// Cierra el archivo
try {
reader.close();
} catch (IOException ex) {

}

// Si se ha encontrado la línea correspondiente
if (found) {
// Asigna los valores a los elementos de la interfaz gráfica de usuario
// Asigna un valor a la etiqueta de estado
status.setText("Modificando");
// Asigna los valores a los campos
nombreCuenta.setText(field2Value);
if (radioButtonValue.equals("1")) {
adm.setSelected(true);
} else {
normal.setSelected(true);
}
padre.setText(field4Value);
grupocOmb.setSelectedItem(comboBox1Value);
if (checkBoxValue.equals("SI")) {
checkBox.setSelected(true);
}
jComboBox2.setSelectedItem(comboBox2Value);
fecha.setText(field7Value);
hora.setText(field8Value);
saldo.setText(label10Value);
} else {
// Asigna un valor a la etiqueta de estado
status.setText("Creando");
// Limpia los campos
nombreCuenta.setText("");
adm.setSelected(false);
normal.setSelected(false);
padre.setText("");
grupocOmb.setSelectedIndex(0);
checkBox.setSelected(false);
jComboBox2.setSelectedIndex(0);
fecha.setText("");
hora.setText("");
saldo.setText("");
}

// Abre el archivo para escritura
BufferedWriter writer = null;
try {
writer = new BufferedWriter(new FileWriter(file));
} catch (IOException ex) {
ex.printStackTrace();
return;
}

// Si se ha encontrado la línea correspondiente
if (found) {
// Modifica la línea correspondiente
String newLine = searchString + "; " + field2Value + "; " + radioButtonValue + "; " + field4Value + "; " + comboBox1Value + "; " + checkBoxValue + "; " + comboBox2Value + "; " + field7Value + "; " + field8Value + "; " + label10Value;
lines.add(newLine);
}

// Escribe cada línea en el archivo
for (String l : lines) {
try {
writer.write(l);
writer.newLine();
} catch (IOException ex) {
ex.printStackTrace();
return;
}
}

// Cierra el archivo
try {
writer.close();
} catch (IOException ex) {

}
}
    public void clear(){
        nombreCuenta.setText("");
adm.setSelected(false);
normal.setSelected(false);
padre.setText("");
grupocOmb.setSelectedIndex(0);
checkBox.setSelected(false);
jComboBox2.setSelectedIndex(0);
fecha.setText("");
hora.setText("");
saldo.setText("");
    }
    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed
public static void setDate(JTextField textField) {
    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    textField.setText(sdf.format(cal.getTime()));
    }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String tipo = "";
        String checkB = ""; 
        //nom,apellid,user,passW,tipo,emaill
        grupo.add(adm);
        grupo.add(normal);
        //adm.setSelected(true);
        if(adm.isSelected()){
            tipo = "GENERAL";
        }else if(normal.isSelected()){
            tipo = "DETALLE";
        }
        String selectedItem = (String) grupocOmb.getSelectedItem();
        if(checkBox.isSelected()){
            checkB = "SI";
        }else{
            checkB = "NO";
        }
        int selectedIndex = jComboBox2.getSelectedIndex();

    // Obtiene el string seleccionado
        String selectedString = (String) jComboBox2.getItemAt(selectedIndex);
        
        //String selectedFlujo = (String) grupocOmb.getSelectedItem();
        saveStrings(numeroCuenta.getText(), nombreCuenta.getText(), tipo, nivel.getText(), padre.getText(), 
                selectedItem, checkB, selectedString, fecha.getText(), hora.getText(), saldo.getText(), debitoAco.getText(), CreditoAco.getText(), ruta);
        clear();
        setDate(fecha);
    }//GEN-LAST:event_aceptarActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked
    public static void saveStrings(String string1, String string2, String string3, String string4, 
            String string5, String string6, String string7, String string8, String string9, 
            String string10, String string11, String string12, String string13, String fileName) {
    try {
      BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));
      writer.write(string1 + "; " + string2 + "; " + string3 + "; " + string4 + "; " + string5 + "; " + string6 + "; " + string7 + "; " + string8 + "; " + string9 + "; " + string10 + "; " + string11 + "; " + string12 + "; " + string13);
      writer.newLine();
      writer.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreditoAco;
    private javax.swing.JButton aceptar;
    private javax.swing.JRadioButton adm;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel debitoAco;
    private javax.swing.JTextField fecha;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JComboBox<String> grupocOmb;
    private javax.swing.JTextField hora;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nivel;
    private javax.swing.JTextField nombreCuenta;
    private javax.swing.JRadioButton normal;
    private javax.swing.JTextField numeroCuenta;
    private javax.swing.JTextField padre;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
