/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SC;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melki
 */
public class ConsultaCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCatalogo
     */
    public ConsultaCatalogo() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();
        todas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(790, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaa.setBackground(new java.awt.Color(204, 255, 204));
        tablaa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Cuenta", "Nombre de Cuenta", "Tipo", "NIvel", "Padre", "Grupo", "Conciliable", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tablaa);
        if (tablaa.getColumnModel().getColumnCount() > 0) {
            tablaa.getColumnModel().getColumn(1).setResizable(false);
            tablaa.getColumnModel().getColumn(1).setPreferredWidth(60);
            tablaa.getColumnModel().getColumn(7).setResizable(false);
            tablaa.getColumnModel().getColumn(7).setPreferredWidth(70);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 760, 330));

        jLabel1.setText("Ingresa el nombre de la Cuenta: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        buscador.setBackground(new java.awt.Color(51, 51, 0));
        buscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscador.setForeground(new java.awt.Color(255, 255, 255));
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        jPanel1.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 32, 230, 40));

        consultar.setBackground(new java.awt.Color(102, 102, 0));
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        todas.setBackground(new java.awt.Color(102, 102, 0));
        todas.setText("Todas");
        todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasActionPerformed(evt);
            }
        });
        jPanel1.add(todas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        
            
        
            searchAndDisplay("catalogo.txt", buscador.getText(), tablaa);
        
        
    }//GEN-LAST:event_consultarActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscadorActionPerformed

    private void todasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasActionPerformed
        // TODO add your handling code here:
        readAndDisplay("catalogo.txt", tablaa);
    }//GEN-LAST:event_todasActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    public static void searchAndDisplay(String fileName, String searchWord, JTable table) {
        // create a BufferedReader object to read the file
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(fileName));

            // create a DefaultTableModel to store the data for the table
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            // clear the existing data in the table
            model.setRowCount(0);

            // read each line of the file
            String line;
            while ((line = reader.readLine()) != null) {
                // split the line into an array of words using "; " as the delimiter
                String[] words = line.split("; ");

                // check if the searchWord is contained in the array of words
                for (String word : words) {
                    if (word.equals(searchWord)) {
                        // the searchWord was found, so display the first 8 words of the line at the top of the table
                        model.insertRow(0, new String[] {words[0], words[1], words[2], words[3], words[4], words[5], words[6], words[10]});
                        break;
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            // close the BufferedReader
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    public static void readAndDisplay(String fileName, JTable table) {
        // create a BufferedReader object to read the file
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(fileName));

            // get the DefaultTableModel of the table
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            // read each line of the file
            String line;
            while ((line = reader.readLine()) != null) {
                // split the line into an array of words using "; " as the delimiter
                String[] words = line.split("; ");

                // add the first 8 words of the line to the table
                model.addRow(new String[] {words[0], words[1], words[2], words[3], words[4], words[5], words[6], words[10]});
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            // close the BufferedReader
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaa;
    private javax.swing.JButton todas;
    // End of variables declaration//GEN-END:variables
}
