/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SC;

import com.toedter.calendar.JDateChooser;
import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author melki
 */
public class Diario extends javax.swing.JFrame {

    /**
     * Creates new form Diario
     */
    String ruta = "Tcabecera.txt", rutaTabla = "Ttabla.txt", rutaCa = "catalogo.txt";
    public Diario() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        procesar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(540, 375));
        jPanel1.setMinimumSize(new java.awt.Dimension(540, 375));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Inicial: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha FInal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, -1));

        fechaInicial.setBackground(new java.awt.Color(0, 51, 51));
        fechaInicial.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 230, 50));

        fechaFinal.setBackground(new java.awt.Color(0, 51, 51));
        fechaFinal.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 230, 50));

        procesar.setBackground(new java.awt.Color(0, 204, 204));
        procesar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        procesar.setForeground(new java.awt.Color(0, 0, 0));
        procesar.setText("Procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });
        jPanel1.add(procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, 60));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 140, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public static void modify1Line(String str, String fileName) throws IOException {
// Create a FileReader to read from the file
FileReader fr = new FileReader(fileName);
// Create a BufferedReader to read from the FileReader
BufferedReader br = new BufferedReader(fr);
// Create a temporary file to store the modified line
File tempFile = new File("temp.txt");
// Create a FileWriter to write to the temporary file
FileWriter fw = new FileWriter(tempFile);
// Create a BufferedWriter to write to the FileWriter
BufferedWriter bw = new BufferedWriter(fw);
// Initialize an array to store the eleventh words of the lines that meet the criteria
    String[] eleventhWords = new String[0];

    // Read each line of the file
    String line;
    while ((line = br.readLine()) != null) {
        // Split the line by "; "
        String[] words = line.split("; ");
        // If the first character of the first word is equal to str and the twelfth word is "0.00"
        // and the first word is not equal to str, store the eleventh word in the array and modify the twelfth word
        if (words[0].charAt(0) == str.charAt(0) && words[11].equals("0") && !words[0].equals(str)) {
            // Add the eleventh word to the array
            eleventhWords = addToArray(eleventhWords, words[10]);
            // Modify the twelfth word to "0"
            words[11] = "0";
            // Rebuild the line with the modified twelfth word
            String modifiedLine = "";
            for (int i = 0; i < words.length; i++) {
                modifiedLine += words[i] + "; ";
            }
            // Write the modified line to the temporary file
            bw.write(modifiedLine);
        }
        // If the line does not meet the criteria or if the first word is equal to str, write it to the temporary file as is
        else {
            bw.write(line);
        }
        // Add a newline character after each line
        bw.newLine();
    }

    // Close the BufferedReader, BufferedWriter, and FileReader
    bw.close();
    br.close();
    fr.close();

    // Delete the original file
    File oldFile = new File(fileName);
    oldFile.delete();
    // Rename the temporary file to the original file
    tempFile.renameTo(oldFile);

    // Calculate the sum of the eleventh words
    double sum = 0;
    for (int i = 0; i < eleventhWords.length; i++) {
        sum += Double.parseDouble(eleventhWords[i]);
    }

    // Reopen the file with a FileReader and BufferedReader
    fr = new FileReader(fileName);
    br = new BufferedReader(fr);
    // Create a new temporary file to store the modified lines
    tempFile = new File("temp.txt");
    // Create a FileWriter to write to the temporary file
fw = new FileWriter(tempFile);
// Create a BufferedWriter to write to the FileWriter
bw = new BufferedWriter(fw);

// Read each line of the file again
while ((line = br.readLine()) != null) {
// Split the line by "; "
String[] words = line.split("; ");
// If the first word is equal to str, modify the eleventh word with the sum
if (words[0].equals(str)) {
// Rebuild the line with the modified eleventh word
String modifiedLine = "";
for (int i = 0; i < words.length; i++) {
// If this is the eleventh word, use the sum
if (i == 10) {
modifiedLine += sum + "; ";
}
// Otherwise, use the original value
else {
modifiedLine += words[i] + "; ";
}
}
// Write the modified line to the temporary file
bw.write(modifiedLine);
}
// If the first word is not equal to str, write the line to the temporary file as is
else {
bw.write(line);
}
// Add a newline character after each line
bw.newLine();
}

// Close the BufferedReader, BufferedWriter, and FileReader
bw.close();
br.close();
fr.close();

// Delete the original file
oldFile.delete();
// Rename the temporary file to the original file
tempFile.renameTo(oldFile);
}
     private static String[] addToArray(String[] arr, String value) {
// Create a new array with one extra element
String[] newArr = new String[arr.length + 1];
// Copy the elements of the original array to the new array
for (int i = 0; i < arr.length; i++) {
newArr[i] = arr[i];
}
// Add the new value to the end of the new array
newArr[arr.length] = value;
return newArr;
}
     
    public static void modifyTextFile(JDateChooser dateChooser1, JDateChooser dateChooser2, String file) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    StringBuilder sb = new StringBuilder();
    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
      String line;
      while ((line = reader.readLine()) != null) {
        String[] parts = line.split("; ");
        if (parts.length >= 2) {
          Date date = dateFormat.parse(parts[1]);
          if (date.after(dateChooser1.getDate()) && date.before(dateChooser2.getDate())) {
            parts[2] = "1";
          }
        }
        sb.append(String.join("; ", parts)).append(System.lineSeparator());
      }
    } catch (IOException | ParseException e) {
      // handle exception
      e.printStackTrace();
    }
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
      writer.write(sb.toString());
    } catch (IOException e) {
      // handle exception
      e.printStackTrace();
    }
  }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed
        try {
                modify1Line("1",rutaCa);
            } catch (IOException ex) {
                Logger.getLogger(transacciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        //modifyTextFile(fechaInicial, fechaFinal, ruta);
    }//GEN-LAST:event_procesarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser fechaFinal;
    public com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton procesar;
    // End of variables declaration//GEN-END:variables
}
