/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SC;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author melki
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        usuarioss = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        transc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        catalogo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        doc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        fecha = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        bala = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jLabel2.setText("jLabel2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wor.gif"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 640));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        bar.setBackground(new java.awt.Color(0, 0, 0));
        bar.setForeground(new java.awt.Color(255, 255, 255));
        bar.setOpaque(true);

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ure.png"))); // NOI18N
        jMenu1.setText("Mantenimieto  ");
        jMenu1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        usuarioss.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        usuarioss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oi_User.png"))); // NOI18N
        usuarioss.setText("Usuarios");
        usuarioss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariossActionPerformed(evt);
            }
        });
        jMenu1.add(usuarioss);
        jMenu1.add(jSeparator1);

        jMenuItem2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cierree.png"))); // NOI18N
        jMenuItem2.setText("Catalogo de Cuenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        bar.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/movimiento.png"))); // NOI18N
        jMenu2.setText("Movimeintos  ");
        jMenu2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        transc.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        transc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trabf.png"))); // NOI18N
        transc.setText("Transacciones");
        transc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcActionPerformed(evt);
            }
        });
        jMenu2.add(transc);

        bar.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procesos.png"))); // NOI18N
        jMenu3.setText("Procesos  ");
        jMenu3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cierree.png"))); // NOI18N
        jMenuItem4.setText("Cierre Diario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);
        jMenu3.add(jSeparator2);

        bar.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consul.png"))); // NOI18N
        jMenu4.setText("Consulta  ");
        jMenu4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N

        catalogo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fis.png"))); // NOI18N
        catalogo.setText("Catalogo de cuentas");
        catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoActionPerformed(evt);
            }
        });
        jMenu4.add(catalogo);
        jMenu4.add(jSeparator3);

        doc.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fis.png"))); // NOI18N
        doc.setText("Documento");
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        jMenu4.add(doc);
        jMenu4.add(jSeparator4);

        fecha.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fis.png"))); // NOI18N
        fecha.setText("Por Fecha");
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jMenu4.add(fecha);
        jMenu4.add(jSeparator5);

        bala.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        bala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fis.png"))); // NOI18N
        bala.setText("Balanza General");
        bala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balaActionPerformed(evt);
            }
        });
        jMenu4.add(bala);

        bar.add(jMenu4);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void transcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcActionPerformed
        // TODO add your handling code here:
        transacciones t = new transacciones();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_transcActionPerformed

    private void usuariossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariossActionPerformed
        // TODO add your handling code here:
        Usuarios use = new Usuarios();
        use.setVisible(true);
        dispose();
    }//GEN-LAST:event_usuariossActionPerformed

    private void catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoActionPerformed
        // TODO add your handling code here:
        ConsultaCatalogo con = new ConsultaCatalogo();
        con.setVisible(true);
        dispose();
    }//GEN-LAST:event_catalogoActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
        ConPorDocumento doc = new ConPorDocumento();
        doc.setVisible(true);
        dispose();
    }//GEN-LAST:event_docActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
        consultaporFecha fec = new consultaporFecha();
        fec.setVisible(true);
        dispose();
    }//GEN-LAST:event_fechaActionPerformed

    private void balaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balaActionPerformed
        // TODO add your handling code here:
        Balanza ba = new Balanza();
        ba.setVisible(true);
        dispose();
    }//GEN-LAST:event_balaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CatalogoCuentas cat = new CatalogoCuentas();
        cat.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Diario dia = new Diario();
        dia.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // UIManager.put("bar.background", Color.ORANGE); //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bala;
    private javax.swing.JMenuBar bar;
    private javax.swing.JMenuItem catalogo;
    private javax.swing.JMenuItem doc;
    private javax.swing.JMenuItem fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem transc;
    private javax.swing.JMenuItem usuarioss;
    // End of variables declaration//GEN-END:variables
}
